version: '3.8'

services:
  # Database service
  database:
    image: postgres:15
    container_name: study-ai-db
    environment:
      POSTGRES_DB: study_ai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - study-ai-network

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: study-ai-redis
    ports:
      - "6379:6379"
    networks:
      - study-ai-network

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: study-ai-backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:password@database:5432/study_ai
      REDIS_URL: redis://redis:6379
    depends_on:
      - database
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - study-ai-network

  # Web frontend service
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: study-ai-web
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: http://localhost:3000
    depends_on:
      - backend
    volumes:
      - ./web:/app
      - /app/node_modules
    networks:
      - study-ai-network

volumes:
  postgres_data:

networks:
  study-ai-network:
    driver: bridge 