"""Add icon and color_theme to subjects table

Revision ID: 356ac195ef03
Revises: 
Create Date: 2025-08-08 04:36:56.863002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '356ac195ef03'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('icon', sa.String(), nullable=True))
    op.add_column('subjects', sa.Column('color_theme', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'color_theme')
    op.drop_column('subjects', 'icon')
    # ### end Alembic commands ###
